# This is a basic workflow to help you get started with Actions

name: "Newman Tests"
on: [push, pull_request]
jobs: 
  build: 
    container: "image:postman/newman"
    runs-on: ubuntu-latest
    steps: 
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: "Run API Tests"
        run: "newman run \"Restful Booker BVT.postman_collection.json\" -e Production.postman_environment.json"
